server:
  port: 8080

spring:
  application:
    name: ai-interview-backend
  
  # MySQL数据库配置
  datasource:
    url: jdbc:mysql://localhost:3306/ai_interview?useSSL=false&serverTimezone=UTC&characterEncoding=utf8&allowPublicKeyRetrieval=true
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root

logging:
  level:
    com.example.aiinterview: DEBUG